services:
  - name: web
    env:
      - key: NODE_ENV
        value: production
    build_command: npm ci
    start_command: npm run start:prod
    prebuild:
      - npm install -g prisma
      - npm install
      - prisma generate
      - prisma migrate deploy
